### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Catyka2** [Catyka2/lectii-HTML#1]
Descriere problema

**Comment by johnsmithm** [comment]
comentariu

**Comment by Catyka2** [comment]
`<div id="menu">	
	<ul>
	    <li>item1</li>
	    <li>item2
		    <ul>
			    <li>item2-1</li>
				<li>item2-2</li>
				<li>item2-3</li>
			</ul>
		</li>
		<li>item3</li>
		<li>item4</li>
	</ul>
</div>	`

**Comment by johnsmithm** [comment]
`<ul><li>kk</li></ul>
`

**Comment by Catyka2** [comment]
> <div id="menu">	
	<ul>
	    <li>item1</li>
	    <li>item2
		    <ul>
			    <li>item2-1</li>
				<li>item2-2</li>
				<li>item2-3</li>
			</ul>
		</li>
		<li>item3</li>
		<li>item4</li>
	</ul>
</div>	

>
