### ISSUE TITLE
functii rezolvare lectie 1

### ISSUE THREAD

**Issue by johnsmithm** [Catyka2/lectii-HTML#4]
2. creaza o functie care ia ca parametrii doua texte si intoarce cuvintele unite
var tt = fexe2('text1','text2') ar trebui ca variabila tt sa devina "text1text2". asta inseamna sa unesti cuvinte.
fexe2 este functia ce trebuia sa o declari, nu sa cauti indicele unde aldoile cuvant apare in primul.

4. creaza un buton si cand apesi pe el sa se apeleze o functie care schimba culoarea textului din pagina in rosu
- merge si asha, dar am vrut sa intelegi cum poti pune in loc de function(){} care e functie fara nume o denumire de functie la click()
ai si exemplu acolo:
```
function ale(){
	alert(1)
}
$('#btn').click(ale)
```

**Comment by Catyka2** [comment]
Multumesc. Am inteles
